Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
  end
  config.vm.network "forwarded_port", guest: 5000, host: 5001, auto_correct: true
  config.vm.synced_folder "../app", "/home/vagrant/app"

  config.vm.provision "shell", path: "provision.sh"
end
